[colors]
[colors.primary]
background = "#222222"
foreground = "#c2c2b0"

[colors.normal]
black   = "#000000"
red     = "#b96f6f"
green   = "#5f875f"
yellow  = "#b36d43"
blue    = "#78824b"
magenta = "#bb7744"
cyan    = "#c9a554"
white   = "#ffffff"

[colors.bright]
black   = "#666666"
red     = "#685742"
green   = "#5f875f"
yellow  = "#b36d43"
blue    = "#78824b"
magenta = "#bb7744"
cyan    = "#c9a554"
white   = "#d7c483"

[colors.cursor]
text   = "#eeeeee"
cursor = "#c7c7c7"
